#############################
#     UltimateParticles     #
#+-------------------------+#
# Authors:                  #
#   - DotNomi               #
#   - Adrijan               #
#+-------------------------+#
# Config-Version: v1        #
#############################

# Global plugin settings
global-settings:
  # Name of the language file you want to use. (Without the .yml)
  language: "english"
  command-alias: "up"

# Image settings
image-settings:
  # Minimum amount of pixels in the X and Y axis. (Must be greater than 0 and smaller than max-size!)
  min-size: 8
  # Maximum amount of pixels in the X and Y axis. (Must be greater than min-size)
  # Important Note: Minecraft can only render approx. 20000 particles at once.
  #                 That means if you have an image with 145x145 (21025) pixels
  #                 it could be that not the whole image is rendered.
  max-size: 128
